[package]
name = "convrs"
version = "0.1.0"
authors = ["Manas Karekar <powerslave12r@gmail.com>"]

[dependencies]
plist = "0.0.15"
handlebars = "0.28.1"

#regex = "0.1.80"
#rustc-serialize = "0.3.19"
#xml-rs = "0.3.4"
