[package]
name = "convrs"
version = "0.1.0"
authors = ["Manas Karekar <powerslave12r@gmail.com>"]

[dependencies]
#plist-rs = "*"
plist = "*"
handlebars = "0.28.1"
clippy = {version = "*", optional = true}
	
#regex = "0.1.80"
#rustc-serialize = "0.3.19"
#xml-rs = "0.3.4"
